### ISSUE TITLE
Adding bar code scanner and 

### ISSUE THREAD

**Issue by papyr** [moemura/BluetoothPrintXamarin#1]
Hi can this be used to connect to a bar code scanner.

also on a side note can you please allow issuesfeature of your admin lte project. I wanted to share some links to bread crumb helpers. I may have a project where you can help (paid)

NwebSec
Recaptca etc that you can plugin

**Comment by moemura** [comment]
Yes, barcode scanner is just seen as keyboard in smartphone. You can see Sunmi code sample.

Done, missed that issues feature.
