### ISSUE TITLE
GOOJPRT PT-210

### ISSUE THREAD

**Issue by IoanaEmma** [moemura/BluetoothPrintXamarin#2]
Can I use this thermal printer with an ASP.NET CORE 3 web app? I'm trying to print a QR code after paypal payment is succesfully executed.

**Comment by moemura** [comment]
Yes, but not directly, need a print service from google play. Free version include header or footer from the app.

**Comment by IoanaEmma** [comment]
Can you give me more details please? After the payment how should I use this print service?

**Comment by moemura** [comment]
If the client is Android turn on bluetooh and pair it. Install printer+ or your choice and configure it. Execute printing from javascript.

if the client is PC then get bluethooh dongle/usb cable install printer driver just like normal printer. Execute printing from javascript.
